In [ ]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import cv2
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
from pygame import mixer

In [12]:
model_folder = "./models/"

In [13]:
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
model = load_model(f"{model_folder}inceptionv3_model.h5")
mixer.init()

In [20]:
mixer.init()
sound= mixer.Sound("../alarm.wav")
cap = cv2.VideoCapture(1)
Score = 0
while True:
    ret, frame = cap.read()
    print(frame)
    height,width = frame.shape[0:2]
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces= face_cascade.detectMultiScale(gray, scaleFactor= 1.2, minNeighbors=3)
    eyes= eye_cascade.detectMultiScale(gray, scaleFactor= 1.1, minNeighbors=1)
    
    cv2.rectangle(frame, (0,height),(400,height),(0,0,0),thickness=cv2.FILLED)
    
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,pt1=(x,y),pt2=(x+w,y+h), color= (255,0,0), thickness=3 )
        
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(frame,pt1=(ex,ey),pt2=(ex+ew,ey+eh), color= (255,0,0), thickness=3 )
        
        # preprocessing steps
        eye= frame[ey:ey+eh,ex:ex+w]
        eye= cv2.resize(eye,(80,80))
        eye= eye/255
        eye= eye.reshape(80,80,3)
        eye= np.expand_dims(eye,axis=0)
        # preprocessing is done now model prediction
        prediction = model.predict(eye)
        
        # if eyes are closed
        if prediction[0][0]>0.70:
            cv2.putText(frame,'closed',(200,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            cv2.putText(frame,'Score'+str(Score),(300,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score=Score+1
            if(Score>15):
                try:
                    sound.play()
                except:
                    pass
            
        # if eyes are open
        elif prediction[0][1]>0.90:
            cv2.putText(frame,'open',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)      
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score = Score - 3
            if Score < 0:
                Score = 0
            
        
    cv2.imshow('frame',frame)
    if cv2.waitKey(33) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

[[[1 3 5]
  [0 1 3]
  [0 0 0]
  ...
  [0 0 0]
  [0 1 1]
  [0 0 0]]

 [[3 4 6]
  [3 4 6]
  [1 3 5]
  ...
  [0 0 0]
  [0 3 2]
  [0 3 2]]

 [[0 2 4]
  [1 3 5]
  [1 3 5]
  ...
  [0 0 0]
  [0 0 0]
  [1 4 4]]

 ...

 [[0 0 0]
  [0 0 0]
  [5 5 4]
  ...
  [0 0 0]
  [2 2 2]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [1 2 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [1 1 1]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[ 78 103 121]
  [ 79 104 123]
  [ 80 105 126]
  ...
  [105 129 152]
  [106 130 153]
  [107 131 154]]

 [[ 77 102 120]
  [ 79 104 123]
  [ 79 104 124]
  ...
  [107 131 154]
  [109 133 155]
  [110 134 156]]

 [[ 78 103 121]
  [ 79 104 123]
  [ 78 103 121]
  ...
  [104 128 149]
  [108 131 151]
  [112 135 157]]

 ...

 [[103  60  40]
  [116  72  50]
  [131  84  58]
  ...
  [ 31  19  25]
  [ 20   7  14]
  [ 21   7  15]]

 [[117  70  43]
  [131  84  57]
  [144  93  55]
  ...
  [ 33  20  26]
  [ 29  11  19]
  [ 28  11  19]]

 [[127  81  53]
  [138  91  60]
  [147  98  62]
  ...
  [ 34

NameError: name 'w' is not defined